---
version: 2
updates:
  - package-ecosystem: pip
    directory: '/'
    schedule:
      interval: daily
      time: '04:00'
    open-pull-requests-limit: 10
    reviewers:
      - sbaerlocher
    assignees:
      - sbaerlocher
    allow:
      - dependency-type: direct
      - dependency-type: indirect
  - package-ecosystem: docker
    directory: '/'
    schedule:
      interval: daily
      time: '04:00'
    open-pull-requests-limit: 10
    reviewers:
      - sbaerlocher
    assignees:
      - sbaerlocher
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '04:00'
    open-pull-requests-limit: 10
    reviewers:
      - sbaerlocher
    assignees:
      - sbaerlocher
